version: '3'

services:
  
  fsh_backend_test:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fsh_backend_test
    ports:
      - "4002:4002"
    expose:
      - 4002
    volumes:
      - .:/app
      - /app/node_modules