services:
  
  fsh_backend_test:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fsh_backend_test
    ports:
      - "4002:4002"
    expose:
      - "4002"
    volumes:
      - .:/app
      - /app/node_modules

  fsh_db_test:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: fsh_db_test
    volumes:
      - ~/apps/fsh_db_test:/var/lib/postgresql/data
    ports:
      - "4003:4003"
    expose:
      - "4003"
    command: -p 4003